import 'package:vaster_context/vaster_context.dart';
import 'package:vaster_model/vaster_model.dart';
import 'package:vaster_token_estimate/vaster_token_estimate.dart';

import 'context_compressor.dart';
import 'truncating_compressor.dart';

/// Model-backed compressor: replaces a region's messages with a single
/// summary generated by [model]. Falls back to deterministic truncation on
/// model failure — compaction must never fail a context compile.
final class SummarizingCompressor implements ContextCompressor {
  static const String defaultTemplate =
      'Summarize the following context ("{label}") into at most {targetTokens} '
      'tokens. Preserve every fact, decision, identifier, and constraint that '
      'later steps might depend on. Output only the summary.\n\n{content}';

  final VasterModel model;
  final String promptTemplate;

  /// When true, original messages are retained in [CompressionInfo] so the
  /// region can be expanded back.
  final bool preserveOriginal;

  final TruncatingCompressor fallback;

  /// Reports each summarization call's usage (measured when the wire provides
  /// it, else a labeled estimate) to the owner that wired this compressor.
  /// Compaction burns real tokens — without this hook they were off-books.
  /// The context subsystem stays unaware of budgets and pricing; it only
  /// measures and reports.
  final void Function(UsageMetadata usage)? onUsage;

  SummarizingCompressor({
    required this.model,
    this.promptTemplate = defaultTemplate,
    this.preserveOriginal = true,
    this.fallback = const TruncatingCompressor(),
    this.onUsage,
  });

  @override
  String get id => 'summarizing:${model.modelName}';

  @override
  ContextCompressibility get level => ContextCompressibility.summarize;

  @override
  Future<CompressionResult> compress(ContextRegion region,
      {required int targetTokens}) async {
    final before = region.estimatedTokens;
    final content = regionContentOf(region);
    final prompt = promptTemplate
        .replaceAll('{label}', region.label)
        .replaceAll('{targetTokens}', '$targetTokens')
        .replaceAll('{content}', content);

    try {
      final response = await model.generate(ModelRequest(
        messages: [ChatMessage.user(prompt)],
        generationConfig: GenerationConfig(
          // Rough chars-per-token headroom for the summary itself.
          maxOutputTokens: (targetTokens * 2).clamp(64, 8192),
        ),
      ));
      onUsage?.call(response.usage.totalTokenCount > 0
          ? response.usage
          : TokenEstimate.forExchange(prompt: prompt, output: response.text));
      final summary = response.text.trim();
      if (summary.isEmpty) {
        return await fallback.compress(region, targetTokens: targetTokens);
      }

      final message =
          ChatMessage.user('[summary of "${region.label}"]: $summary');
      final after = (message.text.length / 4).ceil() + 4;
      final compressed = region.copyWith(
        messages: [message],
        estimatedTokens: after,
        compression: CompressionInfo(
          compressorId: id,
          tokensBefore: before,
          sourceFingerprint: regionFingerprintOf(region),
          lossy: !preserveOriginal,
          originalMessages:
              preserveOriginal ? List<ChatMessage>.of(region.messages) : null,
        ),
      );
      return CompressionResult(
        region: compressed,
        tokensSaved: (before - after).clamp(0, before),
        lossy: !preserveOriginal,
      );
    } catch (_) {
      // Model unavailable/erroring: degrade to deterministic truncation.
      return fallback.compress(region, targetTokens: targetTokens);
    }
  }
}
