import 'file_operation_type.dart';

/// Abstract sealed class representing an event generated during LLM VM runtime execution.
sealed class RuntimeEvent {
  /// Unique event identifier.
  final String eventId;

  /// Timestamp when event was emitted.
  final DateTime timestamp;

  /// Arbitrary event metadata.
  final Map<String, dynamic> metadata;

  RuntimeEvent({
    required this.eventId,
    DateTime? timestamp,
    this.metadata = const {},
  }) : timestamp = timestamp ?? DateTime.now();

  Map<String, dynamic> toJson();
}

/// Emitted when a model generation request starts.
final class ModelStartedEvent extends RuntimeEvent {
  final String sessionId;
  final String modelName;
  final int promptTokenCount;

  ModelStartedEvent({
    required super.eventId,
    required this.sessionId,
    required this.modelName,
    required this.promptTokenCount,
    super.timestamp,
    super.metadata,
  });

  @override
  Map<String, dynamic> toJson() => {
        'type': 'model_started',
        'eventId': eventId,
        'sessionId': sessionId,
        'modelName': modelName,
        'promptTokenCount': promptTokenCount,
        'timestamp': timestamp.toIso8601String(),
      };
}

/// Emitted when a streaming token chunk is generated by a model.
final class ModelTokenGeneratedEvent extends RuntimeEvent {
  final String sessionId;
  final String textDelta;

  ModelTokenGeneratedEvent({
    required super.eventId,
    required this.sessionId,
    required this.textDelta,
    super.timestamp,
    super.metadata,
  });

  @override
  Map<String, dynamic> toJson() => {
        'type': 'model_token_generated',
        'eventId': eventId,
        'sessionId': sessionId,
        'textDelta': textDelta,
        'timestamp': timestamp.toIso8601String(),
      };
}

/// Emitted when model execution completes.
final class ModelFinishedEvent extends RuntimeEvent {
  final String sessionId;
  final String finishReason;
  final int totalTokens;
  final Duration executionDuration;

  ModelFinishedEvent({
    required super.eventId,
    required this.sessionId,
    required this.finishReason,
    required this.totalTokens,
    required this.executionDuration,
    super.timestamp,
    super.metadata,
  });

  @override
  Map<String, dynamic> toJson() => {
        'type': 'model_finished',
        'eventId': eventId,
        'sessionId': sessionId,
        'finishReason': finishReason,
        'totalTokens': totalTokens,
        'executionDurationMs': executionDuration.inMilliseconds,
        'timestamp': timestamp.toIso8601String(),
      };
}

/// Emitted when a tool invocation is called by a model.
final class ToolCalledEvent extends RuntimeEvent {
  final String callId;
  final String toolName;
  final Map<String, dynamic> arguments;

  ToolCalledEvent({
    required super.eventId,
    required this.callId,
    required this.toolName,
    required this.arguments,
    super.timestamp,
    super.metadata,
  });

  @override
  Map<String, dynamic> toJson() => {
        'type': 'tool_called',
        'eventId': eventId,
        'callId': callId,
        'toolName': toolName,
        'arguments': arguments,
        'timestamp': timestamp.toIso8601String(),
      };
}

/// Emitted when a tool execution completes.
final class ToolFinishedEvent extends RuntimeEvent {
  final String callId;
  final String toolName;
  final bool isError;
  final Duration executionDuration;

  ToolFinishedEvent({
    required super.eventId,
    required this.callId,
    required this.toolName,
    required this.isError,
    required this.executionDuration,
    super.timestamp,
    super.metadata,
  });

  @override
  Map<String, dynamic> toJson() => {
        'type': 'tool_finished',
        'eventId': eventId,
        'callId': callId,
        'toolName': toolName,
        'isError': isError,
        'executionDurationMs': executionDuration.inMilliseconds,
        'timestamp': timestamp.toIso8601String(),
      };
}

/// Emitted on virtual filesystem operations.
final class FileOperationEvent extends RuntimeEvent {
  final FileOperationType operation;
  final String path;
  final int sizeBytes;

  FileOperationEvent({
    required super.eventId,
    required this.operation,
    required this.path,
    required this.sizeBytes,
    super.timestamp,
    super.metadata,
  });

  @override
  Map<String, dynamic> toJson() => {
        'type': 'file_operation',
        'eventId': eventId,
        'operation': operation.name,
        'path': path,
        'sizeBytes': sizeBytes,
        'timestamp': timestamp.toIso8601String(),
      };
}

/// Emitted when context regions are evicted from the heap.
final class ContextEvictedEvent extends RuntimeEvent {
  final List<String> evictedRegionIds;
  final int tokensFreed;

  ContextEvictedEvent({
    required super.eventId,
    required this.evictedRegionIds,
    required this.tokensFreed,
    super.timestamp,
    super.metadata,
  });

  @override
  Map<String, dynamic> toJson() => {
        'type': 'context_evicted',
        'eventId': eventId,
        'evictedRegionIds': evictedRegionIds,
        'tokensFreed': tokensFreed,
        'timestamp': timestamp.toIso8601String(),
      };
}

/// Emitted when an isolated code sandbox completes execution.
final class SandboxExecutedEvent extends RuntimeEvent {
  final String sandboxId;
  final String language;
  final int exitCode;
  final Duration executionDuration;

  SandboxExecutedEvent({
    required super.eventId,
    required this.sandboxId,
    required this.language,
    required this.exitCode,
    required this.executionDuration,
    super.timestamp,
    super.metadata,
  });

  @override
  Map<String, dynamic> toJson() => {
        'type': 'sandbox_executed',
        'eventId': eventId,
        'sandboxId': sandboxId,
        'language': language,
        'exitCode': exitCode,
        'executionDurationMs': executionDuration.inMilliseconds,
        'timestamp': timestamp.toIso8601String(),
      };
}
