name: vaster_filesystem_memory
description: In-memory virtual filesystem backend implementation for Vaster.
version: 0.2.0

resolution: workspace

environment:
  sdk: ^3.13.0-282.1.beta

dependencies:
  vaster_filesystem:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
