name: vaster_mmap
description: Zero-Copy POSIX Shared Memory IPC transport for Vaster Model Sidecars using dart:ffi.
version: 0.5.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  ffi: ^2.1.0
  vaster_model:
    path: ../../model/vaster_model

dev_dependencies:
  vaster_instruction:
    path: ../../isa/vaster_instruction
  lints: ^6.0.0
  test: ^1.25.0
