name: vaster_sandbox_process
description: CLI Process code sandbox backend implementation.
version: 0.2.0

resolution: workspace

environment:
  sdk: ^3.13.0-282.1.beta

dependencies:
  vaster_model:
  vaster_sandbox:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
