name: vaster_dis
description: CLI disassembler tool for inspecting and analyzing .vaster bytecode files.
version: 0.2.0

resolution: workspace

environment:
  sdk: ^3.13.0-282.1.beta

executables:
  vaster-dis: vaster_dis

dependencies:
  args: ^2.5.0
  vaster_instruction:
  vaster_runtime:

dev_dependencies:
  vaster_vm:
  vaster_model_fake:
  vaster_agent:
  lints: ^6.0.0
  test: ^1.25.6
