name: vaster_policy_engine
description: Policy evaluation engine and hierarchical containment for Vaster VM.
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.13.0-282.1.beta

dependencies:
  vaster_events:
  vaster_policy:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
